apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: 45644/calendar-sender:1.0