version: '3.9'

services:
  integration_tests:
    build:
      context: ../tests
      dockerfile: Dockerfile
    command: "true"
    environment:
      TESTS_AMQP_DSN: "amqp://guest:guest@rabbitmq:5672/"
      POSTGRES_HOST: "postgres"
    networks:
      - calendar_network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - calendar_network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - calendar_network

  calendar:
    build:
      context: ../
      dockerfile: build/calendar/Dockerfile
    restart: always
    environment:
      DATABASE: sql
      TRANSPORT: http
      sqlHost: postgres
      sqlPort: 5432
      sqlDatabase: "postgres"
    ports:
      - "8088:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - calendar_network

  scheduler:
    build:
      context: ../
      dockerfile: build/scheduler/Dockerfile
    restart: always
    environment:
      sqlHost: postgres
      sqlPort: 5432
      sqlDatabase: "postgres"
      mbHost: rabbitmq
      mbPort: 5672
      mbUsername: "guest"
      mbPassword: "guest"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - calendar_network

  sender:
    build:
      context: ../
      dockerfile: build/sender/Dockerfile
    restart: always
    environment:
      mbHost: rabbitmq
      mbPort: 5672
      mbUsername: "guest"
      mbPassword: "guest"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - calendar_network

networks:
  calendar_network:

volumes:
  postgres-data:

